spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/dbkeda?useUnicode=true&characterEncoding=UTF-8&sessionVariables=FOREIGN_KEY_CHECKS=0&autoReconnect=true
    username: root
    password: root
server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Spring Security配置
#security:
#  user:
#    name: root
#    password: root



